# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_piv_out_opt.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_piv_outopt(object):
    def setupUi(self, Dialog_piv_outopt):
        Dialog_piv_outopt.setObjectName("Dialog_piv_outopt")
        Dialog_piv_outopt.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_piv_outopt.resize(347, 450)
        Dialog_piv_outopt.setMinimumSize(QtCore.QSize(347, 450))
        Dialog_piv_outopt.setMaximumSize(QtCore.QSize(347, 450))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        Dialog_piv_outopt.setFont(font)
        self.pushButton_browse = QtWidgets.QPushButton(Dialog_piv_outopt)
        self.pushButton_browse.setGeometry(QtCore.QRect(304, 30, 30, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_browse.setSizePolicy(sizePolicy)
        self.pushButton_browse.setMinimumSize(QtCore.QSize(30, 23))
        self.pushButton_browse.setMaximumSize(QtCore.QSize(30, 23))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.label_outdir = QtWidgets.QLabel(Dialog_piv_outopt)
        self.label_outdir.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_outdir.setObjectName("label_outdir")
        self.lineEdit_out_dir = QtWidgets.QLineEdit(Dialog_piv_outopt)
        self.lineEdit_out_dir.setGeometry(QtCore.QRect(10, 30, 280, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_dir.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_dir.setSizePolicy(sizePolicy)
        self.lineEdit_out_dir.setMinimumSize(QtCore.QSize(280, 20))
        self.lineEdit_out_dir.setMaximumSize(QtCore.QSize(280, 20))
        self.lineEdit_out_dir.setReadOnly(True)
        self.lineEdit_out_dir.setObjectName("lineEdit_out_dir")
        self.groupBox = QtWidgets.QGroupBox(Dialog_piv_outopt)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 321, 231))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(999, 9999))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_all_seq = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_all_seq.setGeometry(QtCore.QRect(10, 26, 94, 20))
        self.radioButton_all_seq.setChecked(True)
        self.radioButton_all_seq.setObjectName("radioButton_all_seq")
        self.radioButton_specify = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_specify.setGeometry(QtCore.QRect(10, 50, 64, 20))
        self.radioButton_specify.setObjectName("radioButton_specify")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(120, 50, 190, 170))
        self.listWidget.setMinimumSize(QtCore.QSize(190, 170))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 170))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_run = QtWidgets.QPushButton(Dialog_piv_outopt)
        self.pushButton_run.setGeometry(QtCore.QRect(10, 400, 100, 45))
        self.pushButton_run.setMinimumSize(QtCore.QSize(100, 45))
        self.pushButton_run.setMaximumSize(QtCore.QSize(100, 45))
        self.pushButton_run.setObjectName("pushButton_run")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_piv_outopt)
        self.pushButton_cancel.setGeometry(QtCore.QRect(230, 400, 100, 45))
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(100, 45))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.lineEdit_out_dir_2 = QtWidgets.QLineEdit(Dialog_piv_outopt)
        self.lineEdit_out_dir_2.setGeometry(QtCore.QRect(10, 80, 280, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_out_dir_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_out_dir_2.setSizePolicy(sizePolicy)
        self.lineEdit_out_dir_2.setMinimumSize(QtCore.QSize(280, 20))
        self.lineEdit_out_dir_2.setMaximumSize(QtCore.QSize(280, 20))
        self.lineEdit_out_dir_2.setReadOnly(True)
        self.lineEdit_out_dir_2.setObjectName("lineEdit_out_dir_2")
        self.pushButton_browse_2 = QtWidgets.QPushButton(Dialog_piv_outopt)
        self.pushButton_browse_2.setGeometry(QtCore.QRect(304, 80, 30, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_2.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_2.setSizePolicy(sizePolicy)
        self.pushButton_browse_2.setMinimumSize(QtCore.QSize(30, 23))
        self.pushButton_browse_2.setMaximumSize(QtCore.QSize(30, 23))
        self.pushButton_browse_2.setObjectName("pushButton_browse_2")
        self.label_outdir_2 = QtWidgets.QLabel(Dialog_piv_outopt)
        self.label_outdir_2.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.label_outdir_2.setObjectName("label_outdir_2")
        self.label_outdir_3 = QtWidgets.QLabel(Dialog_piv_outopt)
        self.label_outdir_3.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.label_outdir_3.setObjectName("label_outdir_3")
        self.pushButton_browse_3 = QtWidgets.QPushButton(Dialog_piv_outopt)
        self.pushButton_browse_3.setGeometry(QtCore.QRect(304, 130, 30, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_3.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_3.setSizePolicy(sizePolicy)
        self.pushButton_browse_3.setMinimumSize(QtCore.QSize(30, 23))
        self.pushButton_browse_3.setMaximumSize(QtCore.QSize(30, 23))
        self.pushButton_browse_3.setObjectName("pushButton_browse_3")
        self.lineEdit_calib_dir = QtWidgets.QLineEdit(Dialog_piv_outopt)
        self.lineEdit_calib_dir.setGeometry(QtCore.QRect(129, 130, 161, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_calib_dir.sizePolicy().hasHeightForWidth())
        self.lineEdit_calib_dir.setSizePolicy(sizePolicy)
        self.lineEdit_calib_dir.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_calib_dir.setMaximumSize(QtCore.QSize(280, 20))
        self.lineEdit_calib_dir.setReadOnly(True)
        self.lineEdit_calib_dir.setObjectName("lineEdit_calib_dir")
        self.frame = QtWidgets.QFrame(Dialog_piv_outopt)
        self.frame.setGeometry(QtCore.QRect(8, 120, 121, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_no_calib = QtWidgets.QRadioButton(self.frame)
        self.radioButton_no_calib.setChecked(True)
        self.radioButton_no_calib.setObjectName("radioButton_no_calib")
        self.horizontalLayout.addWidget(self.radioButton_no_calib)
        self.radioButton_calib = QtWidgets.QRadioButton(self.frame)
        self.radioButton_calib.setObjectName("radioButton_calib")
        self.horizontalLayout.addWidget(self.radioButton_calib)

        self.retranslateUi(Dialog_piv_outopt)
        QtCore.QMetaObject.connectSlotsByName(Dialog_piv_outopt)

    def retranslateUi(self, Dialog_piv_outopt):
        _translate = QtCore.QCoreApplication.translate
        Dialog_piv_outopt.setWindowTitle(_translate("Dialog_piv_outopt", "Output Options"))
        self.pushButton_browse.setText(_translate("Dialog_piv_outopt", "..."))
        self.label_outdir.setText(_translate("Dialog_piv_outopt", "Velocity Results Directory"))
        self.groupBox.setTitle(_translate("Dialog_piv_outopt", "Select Images to process"))
        self.radioButton_all_seq.setText(_translate("Dialog_piv_outopt", "All sequence"))
        self.radioButton_specify.setText(_translate("Dialog_piv_outopt", "Specify"))
        self.pushButton_run.setText(_translate("Dialog_piv_outopt", "Run"))
        self.pushButton_cancel.setText(_translate("Dialog_piv_outopt", "Cancel"))
        self.pushButton_browse_2.setText(_translate("Dialog_piv_outopt", "..."))
        self.label_outdir_2.setText(_translate("Dialog_piv_outopt", "Parameters ans Grid Directory"))
        self.label_outdir_3.setText(_translate("Dialog_piv_outopt", "Calibration"))
        self.pushButton_browse_3.setText(_translate("Dialog_piv_outopt", "..."))
        self.radioButton_no_calib.setText(_translate("Dialog_piv_outopt", "No"))
        self.radioButton_calib.setText(_translate("Dialog_piv_outopt", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_piv_outopt = QtWidgets.QDialog()
    ui = Ui_Dialog_piv_outopt()
    ui.setupUi(Dialog_piv_outopt)
    Dialog_piv_outopt.show()
    sys.exit(app.exec_())

