# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_pick_grps.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_pick_gprs(object):
    def setupUi(self, Form_pick_gprs):
        Form_pick_gprs.setObjectName("Form_pick_gprs")
        Form_pick_gprs.resize(1100, 784)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        Form_pick_gprs.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form_pick_gprs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_load_grp_img = QtWidgets.QPushButton(Form_pick_gprs)
        self.pushButton_load_grp_img.setMinimumSize(QtCore.QSize(140, 50))
        self.pushButton_load_grp_img.setObjectName("pushButton_load_grp_img")
        self.gridLayout_2.addWidget(self.pushButton_load_grp_img, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 177, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(Form_pick_gprs)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 170))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setChecked(False)
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setFlat(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_3.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_stop.setCheckable(False)
        self.pushButton_stop.setChecked(False)
        self.pushButton_stop.setAutoDefault(False)
        self.pushButton_stop.setFlat(False)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout_3.addWidget(self.pushButton_stop)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_clear.setCheckable(False)
        self.pushButton_clear.setChecked(False)
        self.pushButton_clear.setAutoDefault(False)
        self.pushButton_clear.setFlat(False)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_3.addWidget(self.pushButton_clear)
        self.gridLayout_2.addWidget(self.groupBox, 0, 2, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 177, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 3, 1)
        self.tableWidget_grp = QtWidgets.QTableWidget(Form_pick_gprs)
        self.tableWidget_grp.setMinimumSize(QtCore.QSize(730, 180))
        self.tableWidget_grp.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget_grp.setRowCount(0)
        self.tableWidget_grp.setColumnCount(4)
        self.tableWidget_grp.setObjectName("tableWidget_grp")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grp.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grp.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grp.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_grp.setHorizontalHeaderItem(3, item)
        self.tableWidget_grp.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_grp.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_grp.horizontalHeader().setHighlightSections(True)
        self.tableWidget_grp.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_grp.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget_grp, 0, 4, 3, 1)
        self.pushButton_save = QtWidgets.QPushButton(Form_pick_gprs)
        self.pushButton_save.setMinimumSize(QtCore.QSize(140, 50))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 1, 0, 1, 1)
        self.pushButton_export_csv = QtWidgets.QPushButton(Form_pick_gprs)
        self.pushButton_export_csv.setMinimumSize(QtCore.QSize(140, 50))
        self.pushButton_export_csv.setObjectName("pushButton_export_csv")
        self.gridLayout_2.addWidget(self.pushButton_export_csv, 2, 0, 1, 1)
        self.groupBox_fig = QtWidgets.QGroupBox(Form_pick_gprs)
        self.groupBox_fig.setMinimumSize(QtCore.QSize(1080, 580))
        self.groupBox_fig.setObjectName("groupBox_fig")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_fig)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.groupBox_fig)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_fig, 3, 0, 1, 5)

        self.retranslateUi(Form_pick_gprs)
        QtCore.QMetaObject.connectSlotsByName(Form_pick_gprs)

    def retranslateUi(self, Form_pick_gprs):
        _translate = QtCore.QCoreApplication.translate
        Form_pick_gprs.setWindowTitle(_translate("Form_pick_gprs", "Form"))
        self.pushButton_load_grp_img.setText(_translate("Form_pick_gprs", "Load GRPs image"))
        self.groupBox.setTitle(_translate("Form_pick_gprs", "Pick GRPs"))
        self.pushButton_start.setText(_translate("Form_pick_gprs", "Start"))
        self.pushButton_stop.setText(_translate("Form_pick_gprs", "Stop"))
        self.pushButton_clear.setText(_translate("Form_pick_gprs", "Clear"))
        item = self.tableWidget_grp.horizontalHeaderItem(0)
        item.setText(_translate("Form_pick_gprs", "x (m)"))
        item = self.tableWidget_grp.horizontalHeaderItem(1)
        item.setText(_translate("Form_pick_gprs", "y (m)"))
        item = self.tableWidget_grp.horizontalHeaderItem(2)
        item.setText(_translate("Form_pick_gprs", "j (pix)"))
        item = self.tableWidget_grp.horizontalHeaderItem(3)
        item.setText(_translate("Form_pick_gprs", "i (pix)"))
        self.pushButton_save.setText(_translate("Form_pick_gprs", "Save GRPs results"))
        self.pushButton_export_csv.setText(_translate("Form_pick_gprs", "Export as CSV"))
        self.groupBox_fig.setTitle(_translate("Form_pick_gprs", "Figure"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_pick_gprs = QtWidgets.QWidget()
    ui = Ui_Form_pick_gprs()
    ui.setupUi(Form_pick_gprs)
    Form_pick_gprs.show()
    sys.exit(app.exec_())

