# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_piv_dcc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_piv_dcc(object):
    def setupUi(self, Form_piv_dcc):
        Form_piv_dcc.setObjectName("Form_piv_dcc")
        Form_piv_dcc.resize(1324, 826)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        Form_piv_dcc.setFont(font)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form_piv_dcc)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(Form_piv_dcc)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_img_dir = QtWidgets.QLineEdit(Form_piv_dcc)
        self.lineEdit_img_dir.setMinimumSize(QtCore.QSize(300, 20))
        self.lineEdit_img_dir.setMaximumSize(QtCore.QSize(350, 20))
        self.lineEdit_img_dir.setObjectName("lineEdit_img_dir")
        self.gridLayout_4.addWidget(self.lineEdit_img_dir, 1, 0, 1, 1)
        self.pushButton_browse = QtWidgets.QPushButton(Form_piv_dcc)
        self.pushButton_browse.setMinimumSize(QtCore.QSize(35, 20))
        self.pushButton_browse.setMaximumSize(QtCore.QSize(35, 20))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout_4.addWidget(self.pushButton_browse, 1, 1, 1, 1)
        self.listWidget_img = QtWidgets.QListWidget(Form_piv_dcc)
        self.listWidget_img.setMinimumSize(QtCore.QSize(350, 230))
        self.listWidget_img.setMaximumSize(QtCore.QSize(350, 99999))
        self.listWidget_img.setObjectName("listWidget_img")
        self.gridLayout_4.addWidget(self.listWidget_img, 2, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 833, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 0, 3, 5, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form_piv_dcc)
        self.groupBox_5.setMinimumSize(QtCore.QSize(910, 800))
        self.groupBox_5.setMaximumSize(QtCore.QSize(999999, 999999))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame = QtWidgets.QFrame(self.groupBox_5)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_8.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 4, 5, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form_piv_dcc)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 241))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 360))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_IA = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.label_IA.setFont(font)
        self.label_IA.setObjectName("label_IA")
        self.gridLayout_3.addWidget(self.label_IA, 0, 0, 1, 5)
        self.label_ia_w = QtWidgets.QLabel(self.groupBox_2)
        self.label_ia_w.setObjectName("label_ia_w")
        self.gridLayout_3.addWidget(self.label_ia_w, 1, 0, 1, 1)
        self.spinBox_ia_w = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_ia_w.setMinimum(4)
        self.spinBox_ia_w.setMaximum(512)
        self.spinBox_ia_w.setSingleStep(8)
        self.spinBox_ia_w.setProperty("value", 64)
        self.spinBox_ia_w.setObjectName("spinBox_ia_w")
        self.gridLayout_3.addWidget(self.spinBox_ia_w, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_ia_h = QtWidgets.QLabel(self.groupBox_2)
        self.label_ia_h.setObjectName("label_ia_h")
        self.gridLayout_3.addWidget(self.label_ia_h, 1, 3, 1, 1)
        self.spinBox_ia_h = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_ia_h.setMinimum(4)
        self.spinBox_ia_h.setMaximum(512)
        self.spinBox_ia_h.setSingleStep(8)
        self.spinBox_ia_h.setProperty("value", 64)
        self.spinBox_ia_h.setObjectName("spinBox_ia_h")
        self.gridLayout_3.addWidget(self.spinBox_ia_h, 1, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_5.addWidget(self.line_6, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_SA = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.label_SA.setFont(font)
        self.label_SA.setObjectName("label_SA")
        self.gridLayout.addWidget(self.label_SA, 0, 0, 1, 4)
        self.label_SA_n = QtWidgets.QLabel(self.groupBox_2)
        self.label_SA_n.setObjectName("label_SA_n")
        self.gridLayout.addWidget(self.label_SA_n, 1, 0, 1, 1)
        self.label_SA_s = QtWidgets.QLabel(self.groupBox_2)
        self.label_SA_s.setObjectName("label_SA_s")
        self.gridLayout.addWidget(self.label_SA_s, 1, 1, 1, 1)
        self.label_SA_e = QtWidgets.QLabel(self.groupBox_2)
        self.label_SA_e.setObjectName("label_SA_e")
        self.gridLayout.addWidget(self.label_SA_e, 1, 2, 1, 1)
        self.label_SA_w = QtWidgets.QLabel(self.groupBox_2)
        self.label_SA_w.setObjectName("label_SA_w")
        self.gridLayout.addWidget(self.label_SA_w, 1, 3, 1, 1)
        self.spinBox_sa_n = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_sa_n.setProperty("value", 10)
        self.spinBox_sa_n.setObjectName("spinBox_sa_n")
        self.gridLayout.addWidget(self.spinBox_sa_n, 2, 0, 1, 1)
        self.spinBox_sa_s = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_sa_s.setProperty("value", 10)
        self.spinBox_sa_s.setObjectName("spinBox_sa_s")
        self.gridLayout.addWidget(self.spinBox_sa_s, 2, 1, 1, 1)
        self.spinBox_sa_e = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_sa_e.setProperty("value", 10)
        self.spinBox_sa_e.setObjectName("spinBox_sa_e")
        self.gridLayout.addWidget(self.spinBox_sa_e, 2, 2, 1, 1)
        self.spinBox_sa_w = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_sa_w.setProperty("value", 10)
        self.spinBox_sa_w.setObjectName("spinBox_sa_w")
        self.gridLayout.addWidget(self.spinBox_sa_w, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_tinv = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.label_tinv.setFont(font)
        self.label_tinv.setObjectName("label_tinv")
        self.horizontalLayout.addWidget(self.label_tinv)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.doubleSpinBox_tinv = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_tinv.setDecimals(5)
        self.doubleSpinBox_tinv.setSingleStep(0.0001)
        self.doubleSpinBox_tinv.setProperty("value", 1.0)
        self.doubleSpinBox_tinv.setObjectName("doubleSpinBox_tinv")
        self.horizontalLayout.addWidget(self.doubleSpinBox_tinv)
        self.gridLayout_5.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(289, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form_piv_dcc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(350, 110))
        self.groupBox_4.setMaximumSize(QtCore.QSize(350, 110))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_roi_x = QtWidgets.QLabel(self.groupBox_4)
        self.label_roi_x.setObjectName("label_roi_x")
        self.gridLayout_2.addWidget(self.label_roi_x, 0, 0, 1, 1)
        self.label_roi_y = QtWidgets.QLabel(self.groupBox_4)
        self.label_roi_y.setObjectName("label_roi_y")
        self.gridLayout_2.addWidget(self.label_roi_y, 0, 1, 1, 1)
        self.label_roi_width = QtWidgets.QLabel(self.groupBox_4)
        self.label_roi_width.setObjectName("label_roi_width")
        self.gridLayout_2.addWidget(self.label_roi_width, 0, 2, 1, 1)
        self.label_roi_height = QtWidgets.QLabel(self.groupBox_4)
        self.label_roi_height.setObjectName("label_roi_height")
        self.gridLayout_2.addWidget(self.label_roi_height, 0, 3, 1, 1)
        self.lineEdit_roi_x = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_roi_x.setObjectName("lineEdit_roi_x")
        self.gridLayout_2.addWidget(self.lineEdit_roi_x, 1, 0, 1, 1)
        self.lineEdit_roi_y = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_roi_y.setObjectName("lineEdit_roi_y")
        self.gridLayout_2.addWidget(self.lineEdit_roi_y, 1, 1, 1, 1)
        self.lineEdit_roi_width = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_roi_width.setObjectName("lineEdit_roi_width")
        self.gridLayout_2.addWidget(self.lineEdit_roi_width, 1, 2, 1, 1)
        self.lineEdit_roi_height = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_roi_height.setObjectName("lineEdit_roi_height")
        self.gridLayout_2.addWidget(self.lineEdit_roi_height, 1, 3, 1, 1)
        self.pushButton_draw_roi = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_draw_roi.setObjectName("pushButton_draw_roi")
        self.gridLayout_2.addWidget(self.pushButton_draw_roi, 2, 0, 1, 2)
        self.pushButton_reset_roi = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_reset_roi.setObjectName("pushButton_reset_roi")
        self.gridLayout_2.addWidget(self.pushButton_reset_roi, 2, 2, 1, 2)
        self.gridLayout_6.addWidget(self.groupBox_4, 2, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(Form_piv_dcc)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(350, 110))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Step_x = QtWidgets.QLabel(self.groupBox)
        self.label_Step_x.setObjectName("label_Step_x")
        self.horizontalLayout_2.addWidget(self.label_Step_x)
        self.spinBox_step_x = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_step_x.setMinimum(1)
        self.spinBox_step_x.setMaximum(999)
        self.spinBox_step_x.setProperty("value", 32)
        self.spinBox_step_x.setObjectName("spinBox_step_x")
        self.horizontalLayout_2.addWidget(self.spinBox_step_x)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_Step_y = QtWidgets.QLabel(self.groupBox)
        self.label_Step_y.setObjectName("label_Step_y")
        self.horizontalLayout_2.addWidget(self.label_Step_y)
        self.spinBox_step_y = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_step_y.setMinimum(1)
        self.spinBox_step_y.setMaximum(999)
        self.spinBox_step_y.setProperty("value", 32)
        self.spinBox_step_y.setObjectName("spinBox_step_y")
        self.horizontalLayout_2.addWidget(self.spinBox_step_y)
        self.gridLayout_6.addWidget(self.groupBox, 3, 0, 1, 3)
        self.pushButton_mask = QtWidgets.QPushButton(Form_piv_dcc)
        self.pushButton_mask.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_mask.setMaximumSize(QtCore.QSize(110, 40))
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.gridLayout_6.addWidget(self.pushButton_mask, 4, 0, 1, 1)
        self.pushButton_reset_mask = QtWidgets.QPushButton(Form_piv_dcc)
        self.pushButton_reset_mask.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_reset_mask.setMaximumSize(QtCore.QSize(110, 40))
        self.pushButton_reset_mask.setObjectName("pushButton_reset_mask")
        self.gridLayout_6.addWidget(self.pushButton_reset_mask, 4, 1, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(Form_piv_dcc)
        self.pushButton_run.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButton_run.setMaximumSize(QtCore.QSize(110, 40))
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_6.addWidget(self.pushButton_run, 4, 2, 1, 1)

        self.retranslateUi(Form_piv_dcc)
        QtCore.QMetaObject.connectSlotsByName(Form_piv_dcc)

    def retranslateUi(self, Form_piv_dcc):
        _translate = QtCore.QCoreApplication.translate
        Form_piv_dcc.setWindowTitle(_translate("Form_piv_dcc", "Form"))
        self.label.setText(_translate("Form_piv_dcc", "Image Directory"))
        self.pushButton_browse.setText(_translate("Form_piv_dcc", "..."))
        self.groupBox_5.setTitle(_translate("Form_piv_dcc", "Figure"))
        self.groupBox_2.setTitle(_translate("Form_piv_dcc", "Image Parameter"))
        self.label_IA.setText(_translate("Form_piv_dcc", "Interrogation Area (pix)"))
        self.label_ia_w.setText(_translate("Form_piv_dcc", "Width"))
        self.label_ia_h.setText(_translate("Form_piv_dcc", "Height"))
        self.label_SA.setText(_translate("Form_piv_dcc", "Searching Area (pix)"))
        self.label_SA_n.setText(_translate("Form_piv_dcc", "N"))
        self.label_SA_s.setText(_translate("Form_piv_dcc", "S"))
        self.label_SA_e.setText(_translate("Form_piv_dcc", "E"))
        self.label_SA_w.setText(_translate("Form_piv_dcc", "W"))
        self.label_tinv.setText(_translate("Form_piv_dcc", "Time Interval (sec)"))
        self.groupBox_4.setTitle(_translate("Form_piv_dcc", "ROI"))
        self.label_roi_x.setText(_translate("Form_piv_dcc", "x"))
        self.label_roi_y.setText(_translate("Form_piv_dcc", "y"))
        self.label_roi_width.setText(_translate("Form_piv_dcc", "width"))
        self.label_roi_height.setText(_translate("Form_piv_dcc", "height"))
        self.pushButton_draw_roi.setText(_translate("Form_piv_dcc", "Draw"))
        self.pushButton_reset_roi.setText(_translate("Form_piv_dcc", "Reset"))
        self.groupBox.setTitle(_translate("Form_piv_dcc", "Grid Step"))
        self.label_Step_x.setText(_translate("Form_piv_dcc", "X-dir"))
        self.label_Step_y.setText(_translate("Form_piv_dcc", "Y-dir"))
        self.pushButton_mask.setText(_translate("Form_piv_dcc", "Mask"))
        self.pushButton_reset_mask.setText(_translate("Form_piv_dcc", "Reset Mask"))
        self.pushButton_run.setText(_translate("Form_piv_dcc", "Run..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_piv_dcc = QtWidgets.QWidget()
    ui = Ui_Form_piv_dcc()
    ui.setupUi(Form_piv_dcc)
    Form_piv_dcc.show()
    sys.exit(app.exec_())

