# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_ortho.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_ortho(object):
    def setupUi(self, Form_ortho):
        Form_ortho.setObjectName("Form_ortho")
        Form_ortho.resize(1203, 874)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        Form_ortho.setFont(font)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form_ortho)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form_ortho)
        self.groupBox.setMinimumSize(QtCore.QSize(270, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(270, 99999))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(246, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 5)
        self.label_xmin = QtWidgets.QLabel(self.groupBox)
        self.label_xmin.setObjectName("label_xmin")
        self.gridLayout_2.addWidget(self.label_xmin, 1, 1, 1, 1)
        self.label_xmax = QtWidgets.QLabel(self.groupBox)
        self.label_xmax.setObjectName("label_xmax")
        self.gridLayout_2.addWidget(self.label_xmax, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 69, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 3, 1)
        self.doubleSpinBox_xmin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xmin.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_xmin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_xmin.setDecimals(5)
        self.doubleSpinBox_xmin.setMinimum(-999999.0)
        self.doubleSpinBox_xmin.setMaximum(9999999.0)
        self.doubleSpinBox_xmin.setObjectName("doubleSpinBox_xmin")
        self.gridLayout_2.addWidget(self.doubleSpinBox_xmin, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 69, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 2, 3, 1)
        self.doubleSpinBox_xmax = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xmax.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_xmax.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_xmax.setDecimals(5)
        self.doubleSpinBox_xmax.setMinimum(-999999.0)
        self.doubleSpinBox_xmax.setMaximum(9999999.0)
        self.doubleSpinBox_xmax.setObjectName("doubleSpinBox_xmax")
        self.gridLayout_2.addWidget(self.doubleSpinBox_xmax, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 69, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 4, 3, 1)
        self.label_ymin = QtWidgets.QLabel(self.groupBox)
        self.label_ymin.setObjectName("label_ymin")
        self.gridLayout_2.addWidget(self.label_ymin, 3, 1, 1, 1)
        self.label_ymax = QtWidgets.QLabel(self.groupBox)
        self.label_ymax.setObjectName("label_ymax")
        self.gridLayout_2.addWidget(self.label_ymax, 3, 3, 1, 1)
        self.doubleSpinBox_ymin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ymin.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_ymin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_ymin.setDecimals(5)
        self.doubleSpinBox_ymin.setMinimum(-999999.0)
        self.doubleSpinBox_ymin.setMaximum(9999999.0)
        self.doubleSpinBox_ymin.setObjectName("doubleSpinBox_ymin")
        self.gridLayout_2.addWidget(self.doubleSpinBox_ymin, 4, 1, 1, 1)
        self.doubleSpinBox_ymax = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ymax.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_ymax.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_ymax.setDecimals(5)
        self.doubleSpinBox_ymax.setMinimum(-999999.0)
        self.doubleSpinBox_ymax.setMaximum(9999999.0)
        self.doubleSpinBox_ymax.setObjectName("doubleSpinBox_ymax")
        self.gridLayout_2.addWidget(self.doubleSpinBox_ymax, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(246, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 5)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 853, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 0, 3, 4, 1)
        self.groupBox_fig = QtWidgets.QGroupBox(Form_ortho)
        self.groupBox_fig.setMinimumSize(QtCore.QSize(880, 850))
        self.groupBox_fig.setObjectName("groupBox_fig")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_fig)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.groupBox_fig)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_fig, 0, 4, 4, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form_ortho)
        self.groupBox_2.setMinimumSize(QtCore.QSize(270, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(270, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_manual = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.gridLayout_3.addWidget(self.radioButton_manual, 1, 1, 1, 1)
        self.label_default_res = QtWidgets.QLabel(self.groupBox_2)
        self.label_default_res.setText("")
        self.label_default_res.setObjectName("label_default_res")
        self.gridLayout_3.addWidget(self.label_default_res, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 2, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 0, 3, 2, 1)
        self.doubleSpinBox_res = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_res.setDecimals(7)
        self.doubleSpinBox_res.setSingleStep(0.01)
        self.doubleSpinBox_res.setObjectName("doubleSpinBox_res")
        self.gridLayout_3.addWidget(self.doubleSpinBox_res, 1, 2, 1, 1)
        self.radioButton_default = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_default.setChecked(True)
        self.radioButton_default.setObjectName("radioButton_default")
        self.gridLayout_3.addWidget(self.radioButton_default, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.pushButton_browse = QtWidgets.QPushButton(Form_ortho)
        self.pushButton_browse.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_browse.setMaximumSize(QtCore.QSize(86, 30))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout_4.addWidget(self.pushButton_browse, 2, 0, 1, 1)
        self.pushButton_preview = QtWidgets.QPushButton(Form_ortho)
        self.pushButton_preview.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_preview.setMaximumSize(QtCore.QSize(86, 30))
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.gridLayout_4.addWidget(self.pushButton_preview, 2, 1, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(Form_ortho)
        self.pushButton_run.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_run.setMaximumSize(QtCore.QSize(86, 30))
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout_4.addWidget(self.pushButton_run, 2, 2, 1, 1)
        self.listWidget_image_list = QtWidgets.QListWidget(Form_ortho)
        self.listWidget_image_list.setMinimumSize(QtCore.QSize(270, 450))
        self.listWidget_image_list.setMaximumSize(QtCore.QSize(270, 16777215))
        self.listWidget_image_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_image_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_image_list.setObjectName("listWidget_image_list")
        self.gridLayout_4.addWidget(self.listWidget_image_list, 3, 0, 1, 3)

        self.retranslateUi(Form_ortho)
        QtCore.QMetaObject.connectSlotsByName(Form_ortho)

    def retranslateUi(self, Form_ortho):
        _translate = QtCore.QCoreApplication.translate
        Form_ortho.setWindowTitle(_translate("Form_ortho", "Form"))
        self.groupBox.setTitle(_translate("Form_ortho", "Edge"))
        self.label_xmin.setText(_translate("Form_ortho", "x min"))
        self.label_xmax.setText(_translate("Form_ortho", "x max"))
        self.label_ymin.setText(_translate("Form_ortho", "y min"))
        self.label_ymax.setText(_translate("Form_ortho", "y max"))
        self.groupBox_fig.setTitle(_translate("Form_ortho", "Figure"))
        self.groupBox_2.setTitle(_translate("Form_ortho", "Resolution (m/pix)"))
        self.radioButton_manual.setText(_translate("Form_ortho", "Manual"))
        self.radioButton_default.setText(_translate("Form_ortho", "Default"))
        self.pushButton_browse.setText(_translate("Form_ortho", "Browse"))
        self.pushButton_preview.setText(_translate("Form_ortho", "Preview"))
        self.pushButton_run.setText(_translate("Form_ortho", "Run..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_ortho = QtWidgets.QWidget()
    ui = Ui_Form_ortho()
    ui.setupUi(Form_ortho)
    Form_ortho.show()
    sys.exit(app.exec_())

